-- 코드를 입력하세요
# 상품코드 별 매출액(판매가 * 판매량) 합계
# PRODUCT_CODE, SALES
SELECT PRODUCT_CODE, SUM(PRICE * sale.SALES_AMOUNT) as SALES
FROM PRODUCT as p
JOIN OFFLINE_SALE AS sale ON p.PRODUCT_ID = sale.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;

# SELECT * FROM PRODUCT;